version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./sale-service/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  ## Tempo
  my-tempo:
    image: grafana/tempo:2.7.0-rc.0
    container_name: my-tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./sale-service/docker/tempo/tempo.yml:/etc/tempo.yaml:ro
      - ./sale-service/docker/tempo/tempo-data:/tmp/tempo
    ports:
      - "3200:3200" # Tempo
      - "9411:9411" # zipkin

  my-loki:
    image: grafana/loki:main
    container_name: my-loki
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"

  my-grafana:
    image: grafana/grafana
    container_name: my-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./sale-service/docker/grafana:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password

  user-service:
    image: user-service
    ports:
      - "8000:8000"
  client-service:
    image: client-service
    ports:
      - "4000:3000"
  sale-service:
    image: sale-service
    depends_on:
      - my-tempo
      - my-loki
    restart: always
    ports:
      - "8085:8085"
