# client-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service
  namespace: crm-namespace  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client-service
  template:
    metadata:
      labels:
        app: client-service
    spec:
      containers:
      - name: client-microservice2
        image: ghad2001/client-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: DAPR_HTTP_PORT
          value: "3500"
        - name: DAPR_GRPC_PORT
          value: "50001"
        args:
        - "--app-id"
        - "client-service"
