apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: crm-namespace
spec:
  selector:
    app: client-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
