apiVersion: v1
kind: Service
metadata:
  name: sale-service
  namespace: crm-namespace
spec:
  selector:
    app: sale-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
