apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: crm-namespace
spec:
  selector:
    app: user-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
